<Workspace Version="1.3.2.2480" X="168.270804270565" Y="80.0968135904448" zoom="1.0247286933445" ScaleFactor="1" Name="Springs.Beams.FixExtents" Description="Detects all beams from the input list with broken extents(actual length - cut length &lt;  margin) and attemts to correct them." ID="7ae83d0d-faed-43ba-ae85-fdd942b47e2d" Category="Springs.Revit.Utility">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="788.50601956522" y="169.586380570722" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="la = str1.GetParameterValueByName(&quot;Length&quot;);&#xA;lb = str1.GetParameterValueByName(&quot;Cut Length&quot;);&#xA;mask1  = Math.Abs(la - lb) &gt; margin;&#xA;DSCore.List.FilterByBoolMask(str1,mask1)[&quot;in&quot;];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="6826ab31-96ff-4e52-8ee9-78f3a09e8d49" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1303.29628211907" y="218.330529182968" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB.Structure import StructuralFramingUtils

clr.AddReference("System")
from System.Collections.Generic import List as cList

def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]

beams = UnwrapElement(tolist(IN[0]))

TransactionManager.Instance.EnsureInTransaction(doc)
for b in beams:
	try:
		StructuralFramingUtils.DisallowJoinAtEnd(b,0)
		StructuralFramingUtils.DisallowJoinAtEnd(b,1)
	except:
		pass
		
ids1 = [e.Id for e in beams]
ids2 = cList[ElementId](ids1)
uidoc.Selection.SetElementIds(ids2)
OUT = "%s beams corrected in Revit." %ids2.Count
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0e242a3e-c651-4aa9-b8ba-d479bb00bc48" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="174.182959101147" y="134.727742893523" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;framing&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d34959a1-f9bf-4cc7-8831-da399c6b279f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-53.6318720767829" y="4.4386532831431" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="beams:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="52d80ced-cff5-4359-b259-9417e874ffb0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-47.3443385878088" y="195.467658439647" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="margin:double = 250" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5b762c6c-eaf4-4b2c-a5ee-bc6d3cf40f64" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1456.38060810672" y="217.839883706231" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="45a0fb48-d596-4710-aed7-b8e8d978caaa" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Springs.Filter.ByClassName" x="328.41109235316" y="75.2926953067142" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="False" />
      <ID value="3760b286-a8de-438d-9238-c6755dc9c862" />
      <Name value="Filter.ByClassName" />
      <Description value="Filters a list of objects by the object's class name. Note that Dynamo elements belong to different classes than their Revit counterparts. Use the Object.Class node to check an object's class." />
      <Inputs>
        <Input value="object" />
        <Input value="optionalName" />
        <Input value="className" />
      </Inputs>
      <Outputs>
        <Output value="bool" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e230552a-6916-4aed-b6e0-e7ab0db6c3bb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="582.486585616605" y="12.3499769514378" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="44b945fd-74d6-40d9-99e0-c8bad98326ed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-54.5074342049435" y="271.873351918282" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="refresh:bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" start_index="3" end="6826ab31-96ff-4e52-8ee9-78f3a09e8d49" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6826ab31-96ff-4e52-8ee9-78f3a09e8d49" start_index="0" end="5b762c6c-eaf4-4b2c-a5ee-bc6d3cf40f64" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e242a3e-c651-4aa9-b8ba-d479bb00bc48" start_index="0" end="45a0fb48-d596-4710-aed7-b8e8d978caaa" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d34959a1-f9bf-4cc7-8831-da399c6b279f" start_index="0" end="45a0fb48-d596-4710-aed7-b8e8d978caaa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d34959a1-f9bf-4cc7-8831-da399c6b279f" start_index="0" end="e230552a-6916-4aed-b6e0-e7ab0db6c3bb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52d80ced-cff5-4359-b259-9417e874ffb0" start_index="0" end="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45a0fb48-d596-4710-aed7-b8e8d978caaa" start_index="0" end="e230552a-6916-4aed-b6e0-e7ab0db6c3bb" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e230552a-6916-4aed-b6e0-e7ab0db6c3bb" start_index="0" end="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>