<Workspace Version="1.3.2.2480" X="81.825" Y="174.78" zoom="1.1575" ScaleFactor="1" Name="Springs.Collector.AllElementsOf" Description="Depreciated, use the Springs.Collector.AllElementsOf+ version instead.&#xD;&#xA;&#xD;&#xA;Works with either categories or types and uses the built in collecotor functions. Can be applied as a function. No ties to the Document.Changed event." ID="354b9db1-4f8c-4cda-b2e5-757d8028d8d6" Category="Springs._Depreciated">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point.ByCoordinates" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Polygon" resolvedName="Autodesk.DesignScript.Geometry.Polygon" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Display" resolvedName="Display.Display" assemblyName="Display.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Autodesk.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="BoundingBox" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="ElementQueries.OfCategory" resolvedName="Revit.Elements.InternalUtilities.ElementQueries" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="ElementQueries.OfElementType" resolvedName="Revit.Elements.InternalUtilities.ElementQueries" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="DSCore.Object" resolvedName="DSCore.Object" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="ElementQueries" resolvedName="Revit.Elements.InternalUtilities.ElementQueries" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6f802bf0-d302-4eda-aee3-2eef4dfea99e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="el = [Imperative]{&#xA;isType = String.StartsWith(ToString(x), &quot;Autodesk.Revit.DB.&quot;, 0);&#xA;if (isType)&#xA;{&#xA;  return = ElementQueries.OfElementType(x);&#xA;}&#xA;else&#xA;{&#xA;  return = ElementQueries.OfCategory(x);&#xA;}};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6242af6b-95de-4320-8b7a-de50a0ffe821" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="4.31965442764567" y="-3.45572354211663" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="CategoryOrType: var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4be01959-c3b7-45b1-b393-bedce9267bbe" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="866.803455723543" y="1.72786177105831" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9c0f7040-2f90-4498-9cca-fa3c0c58a8f8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="4.23498920086388" y="57.4393088552916" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="refresh:bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6f802bf0-d302-4eda-aee3-2eef4dfea99e" start_index="0" end="4be01959-c3b7-45b1-b393-bedce9267bbe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6242af6b-95de-4320-8b7a-de50a0ffe821" start_index="0" end="6f802bf0-d302-4eda-aee3-2eef4dfea99e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>