<Workspace Version="1.3.2.2480" X="-247.302565242704" Y="206.004863419799" zoom="2.26511812821295" ScaleFactor="1" Name="Springs.DirectShape.Transform" Description="Transforms the typed DirectShape element from the identity coordinate system to the input coordinate system(s), in a manner similar to Dynamo's Geometry.Transform node." ID="12780047-c2ae-4b94-bb43-6408c7dbd8ef" Category="Springs.Revit.DirectShape">
  <NamespaceResolutionMap>
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane.XY" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="8e8f02c4-80f0-4d4b-a41d-7794c28705d4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="187.158521920979" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
isRvt2017 = int(app.VersionNumber) &gt; 2016

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

units = doc.GetUnits().GetFormatOptions(UnitType.UT_Length).DisplayUnits
factor = 1 / UnitUtils.ConvertToInternalUnits(1,units)

def cs2Trans(cs, scale = factor):
	tf1 = Transform(Transform.Identity)
	tf1.Origin = cs.Origin.ToXyz(True)
	tf1.Basis[0] = cs.XAxis.ToXyz(True)
	tf1.Basis[1] = cs.YAxis.ToXyz(True)
	tf1.Basis[2] = cs.ZAxis.ToXyz(True)
	return tf1.ScaleBasis(scale)

dsTyped = UnwrapElement(IN[0])
cs1 = tolist(IN[1])

transforms = map(cs2Trans, cs1)
cat = dsTyped.Category
TypeId = dsTyped.GetTypeId()
Lib_TypeId = TypeId.ToString()
dsLib = DirectShapeLibrary.GetDirectShapeLibrary(doc)
if not dsLib.ContainsType(Lib_TypeId): dsLib.AddDefinitionType(Lib_TypeId, TypeId)

def TransformDS(transf):
	try:
		if isRvt2017:
			ds1 = DirectShape.CreateElementInstance(doc, TypeId, cat.Id, Lib_TypeId, transf)
		else:
			ds1 = DirectShape.CreateElementInstance(doc, TypeId, cat.Id, Lib_TypeId, transf, "Dynamo","spring nodes"
		ds1.SetTypeId(TypeId)
		return ds1.ToDSType(False)
	except: return None
	
TransactionManager.Instance.EnsureInTransaction(doc)
OUT = map(TransformDS, transforms)
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b3522dbf-d73c-43aa-ba7a-e47a5cc15bfe" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="directShape:var " />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5a074050-f54e-47c0-9942-5d7ed48c3283" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-10.1582513734547" y="59.9368903321445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="coordSystem:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6e27f05e-f107-40dc-97aa-1feeca987a8f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="346.6" y="0.800000000000011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="directShape" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8e8f02c4-80f0-4d4b-a41d-7794c28705d4" start_index="0" end="6e27f05e-f107-40dc-97aa-1feeca987a8f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b3522dbf-d73c-43aa-ba7a-e47a5cc15bfe" start_index="0" end="8e8f02c4-80f0-4d4b-a41d-7794c28705d4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a074050-f54e-47c0-9942-5d7ed48c3283" start_index="0" end="8e8f02c4-80f0-4d4b-a41d-7794c28705d4" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>