<Workspace Version="1.3.1.1736" X="-13.0706922006215" Y="134.812825236355" zoom="1.27771698410772" ScaleFactor="1" Name="Springs.Element.SetLocation" Description="Attempts to modify the location of the input element. This can effectively add as a move comand in Revit. Works for both line based and point based elements." ID="bac5c146-7610-4c0b-a9b1-7a7aeb13bb2b" Category="Springs.Revit.Element">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="61e46993-03f6-4a2e-9726-c414ed48bb4e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="62.4336804095385" y="-2.05223349137634" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ae6130ca-5464-4075-8f5d-f9240228246a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="54.712030646603" y="60.7477665086237" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="location:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="75586c6e-832e-4bda-97b9-da911b3c771e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="376.619736891699" y="-1.2522334913763" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="c2d8deac-6440-4913-95bd-5d08d2a6f123" type="PythonNodeModels.PythonNode" nickname="Python Script" x="224.950259359426" y="-0.150734336487744" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc =  DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import StructuralFramingUtils, StructuralType
FrU = StructuralFramingUtils

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

elements = UnwrapElement(tolist(IN[0]))
newloc = UnwrapElement(tolist(IN[1]))
out1 = []
framing = ("Beam", "Brace")

TransactionManager.Instance.EnsureInTransaction(doc)
for i in xrange(len(elements)):
	try:
		el_typ = elements[i].GetType().ToString()
		isWall, isBeam = False, False
		if el_typ == "Autodesk.Revit.DB.Wall":
			w_start = WallUtils.IsWallJoinAllowedAtEnd(elements[i],0)
			w_end = WallUtils.IsWallJoinAllowedAtEnd(elements[i],1)
			WallUtils.DisallowWallJoinAtEnd(elements[i],0)
			WallUtils.DisallowWallJoinAtEnd(elements[i],1)
			isWall = True
		elif el_typ == "Autodesk.Revit.DB.FamilyInstance":
			if elements[i].StructuralType.ToString() in framing:
				b_start = FrU.IsJoinAllowedAtEnd(elements[i],0)
				b_end = FrU.IsJoinAllowedAtEnd(elements[i],1)
				FrU.DisallowJoinAtEnd(elements[i],0)
				FrU.DisallowJoinAtEnd(elements[i],1)
				isBeam = True	
		newloc1 = newloc[i].ToRevitType()
		oldloc = elements[i].Location
		loc_typ = oldloc.GetType().ToString()
		if loc_typ == "Autodesk.Revit.DB.LocationCurve":
			oldloc.Curve = newloc1
		elif loc_typ == "Autodesk.Revit.DB.LocationPoint":
			oldloc.Point = newloc1
		if isWall:
			if w_start: WallUtils.AllowWallJoinAtEnd(elements[i],0)
			if w_end: WallUtils.AllowWallJoinAtEnd(elements[i],1)
		if isBeam:
			if b_start: FrU.AllowJoinAtEnd(elements[i],0)
			if b_end: FrU.AllowJoinAtEnd(elements[i],1)
		out1.append(elements[i].ToDSType(True))
	except:
		out1.append(None)
TransactionManager.Instance.TransactionTaskDone()

OUT = out1</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="61e46993-03f6-4a2e-9726-c414ed48bb4e" start_index="0" end="c2d8deac-6440-4913-95bd-5d08d2a6f123" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae6130ca-5464-4075-8f5d-f9240228246a" start_index="0" end="c2d8deac-6440-4913-95bd-5d08d2a6f123" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2d8deac-6440-4913-95bd-5d08d2a6f123" start_index="0" end="75586c6e-832e-4bda-97b9-da911b3c771e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="28.1210126766283" eyeY="51.1483487654114" eyeZ="53.2504072098136" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>