<Workspace Version="1.2.1.3083" X="211.182559200034" Y="97.6636844236248" zoom="1.545620359375" Name="Springs.Element.RemoveVoidCut" Description="Removes the void cut between the input elements, if such exists." ID="8e939b52-ea4c-41ff-97bb-f54ba062c938" Category="Springs.Revit.Element">
  <NamespaceResolutionMap>
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Cuboid.ByLengths" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="6451a467-72c7-440f-b8c5-4bd2791f6c5d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="225.155606765216" y="-1.55277457717398" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Copyright(c) 2017, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com
# www.badmonkeys.net

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

def singleton(x):
	if hasattr(x,'__iter__'): return x[0]
	else : return x

elem = UnwrapElement(singleton(IN[0]) )
cuts = UnwrapElement(tolist(IN[1]) )
out1 = []

cutU = InstanceVoidCutUtils
OUT = 0
if cutU.CanBeCutWithVoid(elem):
	TransactionManager.Instance.EnsureInTransaction(doc)
	for c in cuts:
		if cutU.IsVoidInstanceCuttingElement(c) and \
		cutU.InstanceVoidCutExists(elem, c):
			try:
				cutU.RemoveInstanceVoidCut(doc,ToBeCut[i],Cuts[j])
				OUT += 1
			except:
				pass
	TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9ff9dc4c-45aa-4c03-a2a5-6de0b141d8c3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-8.79905593731912" y="2.8421709430404E-14" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elementBeingCut:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="eb7e5e33-5f47-4d5f-8ae3-c16b6a9acf02" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-17.0805203489137" y="59.421482998185" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="cuttingElement:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4426ed96-35ed-4c7d-9f75-caaf24685997" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="381.477918604345" y="-1.55277457717398" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="uncutCount" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6451a467-72c7-440f-b8c5-4bd2791f6c5d" start_index="0" end="4426ed96-35ed-4c7d-9f75-caaf24685997" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ff9dc4c-45aa-4c03-a2a5-6de0b141d8c3" start_index="0" end="6451a467-72c7-440f-b8c5-4bd2791f6c5d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eb7e5e33-5f47-4d5f-8ae3-c16b6a9acf02" start_index="0" end="6451a467-72c7-440f-b8c5-4bd2791f6c5d" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>