<Workspace Version="1.0.0.1180" X="259.400187921041" Y="157.042783848514" zoom="1.21316139457394" Name="Springs.FamilyInstance.ByGeometry" Description="You must provide a valid family template path that will be used for all input geometry objects. The project units(and not the templates) will be used to determine the size of the output geometry.&#xD;&#xA;The provided category will be used only if the family template supports it. If not, the default template category will be used instead.&#xD;&#xA;Likewise, the family material(provided as a string) will be set only if a material with that name exists in the template. If not, the default material will be used instead (&quot;By Category&quot;).&#xD;&#xA;For void cuts, the material settings will be ignored.&#xD;&#xA;The Subcategory name is an optional input. If you'd like to skip assigning a Subcategory to any new instance, simply use null.&#xD;&#xA;The node expects a unique family name for each geometry object. The rest of the input lists will be processed as if the node lacing is set to longest." ID="ecdb3729-0de2-4c50-bdca-28fe881027a2" Category="Springs.Revit.FamilyInstance">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="CoordinateSystem" resolvedName="Autodesk.DesignScript.Geometry.CoordinateSystem" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="FamilyInstance" resolvedName="Revit.Elements.FamilyInstance" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="1cc92fa8-a1b1-4217-a336-0a638867f39c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="193.874021205893" y="98.5069454669779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="7">
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr
import System
from System.Collections.Generic import *

from itertools import repeat

pf_path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.ProgramFilesX86)
import sys
sys.path.append("%s\IronPython 2.7\Lib" %pf_path)
import traceback

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
from Autodesk.DesignScript.Geometry import Point as DynPoint

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import StructuralType

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

def output1(l1):
	if len(l1) == 1: return l1[0]
	else: return l1

def PadLists(lists):
	len1 = len(lists[0])
	for i in xrange(1,len(lists)):
		len2 = len(lists[i])
		if len2 == len1 : continue
		elif len2 &gt; len1: lists[i] = lists[i][:len1]
		else : lists[i].extend(repeat(lists[i][-1],len1 - len2))
	return lists

class FamOpt1(IFamilyLoadOptions):
	def __init__(self):
		pass
	def OnFamilyFound(self,familyInUse, overwriteParameterValues):
		return True
	def OnSharedFamilyFound(self,familyInUse, source, overwriteParameterValues):
		return True

geom = tolist(IN[0])
fam_path = IN[1]
names = tolist(IN[2])
category = tolist(IN[3])
material = tolist(IN[4])
isVoid = tolist(IN[5])
subcat = tolist(IN[6])

units = doc.GetUnits().GetFormatOptions(UnitType.UT_Length).DisplayUnits
factor = UnitUtils.ConvertToInternalUnits(1,units)
acceptable_views = ("ThreeD", "FloorPlan", "EngineeringPlan", "CeilingPlan", "Elevation", "Section")
origin = XYZ(0,0,0)
str_typ = StructuralType.NonStructural
t1 = TransactionManager.Instance
temp_path = System.IO.Path.GetTempPath()
satOpt = SATImportOptions()
satOpt.Placement = ImportPlacement.Origin
satOpt.Unit = ImportUnit.Foot
opt1 = Options()
opt1.ComputeReferences = True
SaveAsOpt = SaveAsOptions()
SaveAsOpt.OverwriteExistingFile = True

def NewForm_background(s1, name1, cat1, isVoid1, mat1, subcat1):
	enable_mat = False if mat1 is None else True
	enable_subcat = False if subcat1 is None else True
	TransactionManager.ForceCloseTransaction(t1)
	famdoc = doc.Application.NewFamilyDocument(fam_path)
	message = None
	temp_path = System.IO.Path.GetTempPath()
	sat_path = "%s%s.sat" % (temp_path, name1)
	try:
		if factor != 1:
			s1 = s1.Scale(factor)
		vec1 = Vector.ByTwoPoints(BoundingBox.ByGeometry(s1).MinPoint, DynPoint.Origin())
		s1 = s1.Translate(vec1)
		sat1 = Geometry.ExportToSAT(s1, sat_path)
		view_fec = FilteredElementCollector(famdoc).OfClass(View)
		view1 = None
		for v in view_fec:
			if str(v.ViewType) in acceptable_views and not v.IsTemplate:
				view1 = v
				break
		t1.EnsureInTransaction(famdoc)
		satId = famdoc.Import(sat1, satOpt, view1)
		el1 = famdoc.GetElement(satId)
		geom1 = el1.get_Geometry(opt1)
		enum = geom1.GetEnumerator()
		enum.MoveNext()
		geom2 = enum.Current.GetInstanceGeometry()
		enum2 = geom2.GetEnumerator()
		enum2.MoveNext()
		s1 = enum2.Current
		famdoc.Delete(satId)
		System.IO.File.Delete(sat_path)
	except:
		message = (traceback.format_exc(),"")
		pass
	if message is None:
		try:
			save_path = "%s%s.rfa" % (temp_path, name1)
			try: #set the category
				fam_cat = famdoc.Settings.Categories.get_Item(cat1.Name)
				famdoc.OwnerFamily.FamilyCategory = fam_cat
			except: pass
			s2 = FreeFormElement.Create(famdoc,s1)
			if isVoid1:
				void_par = s2.get_Parameter(BuiltInParameter.ELEMENT_IS_CUTTING).Set(1)
				void_par2 = famdoc.OwnerFamily.get_Parameter(BuiltInParameter.FAMILY_ALLOW_CUT_WITH_VOIDS).Set(1)
			else: #voids do not have a material values or a sub-cateogry
				if enable_mat:
					try:
						mat_fec = FilteredElementCollector(famdoc).OfClass(Material)
						for m in mat_fec:
							if m.Name == mat1:
								fam_mat = m
								break
						mat_par = s2.get_Parameter(BuiltInParameter.MATERIAL_ID_PARAM).Set(fam_mat.Id)
					except: pass
				if enable_subcat: #create and assign the sub-category:
					try:
						current_fam_cat = famdoc.OwnerFamily.FamilyCategory
						new_subcat = famdoc.Settings.Categories.NewSubcategory(current_fam_cat, subcat1)
						s2.Subcategory = new_subcat
					except: pass
			TransactionManager.ForceCloseTransaction(t1)
			famdoc.SaveAs(save_path, SaveAsOpt)
			family1 = famdoc.LoadFamily(doc, FamOpt1() )
			famdoc.Close(False)
			System.IO.File.Delete(save_path)
			symbols = family1.GetFamilySymbolIds().GetEnumerator()
			symbols.MoveNext()
			symbol1 = doc.GetElement(symbols.Current)
			t1.EnsureInTransaction(doc)
			if not symbol1.IsActive: symbol1.Activate()
			inst1 = doc.Create.NewFamilyInstance(origin, symbol1, str_typ)
			ElementTransformUtils.MoveElement(doc,inst1.Id, vec1.Reverse().ToXyz() )
			TransactionManager.ForceCloseTransaction(t1)
			return inst1.ToDSType(False), family1.ToDSType(False)
		except:
			message = (traceback.format_exc(),"")
			return message
	else : return message

if len(geom) == len(names) == len(category) == len(isVoid) == len(material) == len(subcat):
	return1 = map(NewForm_background, geom, names, category, isVoid, material, subcat)
elif len(geom) == len(names):
	padded = PadLists([geom, category, isVoid, material,subcat])
	p_category, p_isVoid, p_material, p_subcat = padded[1], padded[2], padded[3], padded[4]
	return1 = map(NewForm_background, geom, names, p_category, p_isVoid, p_material, p_subcat)
else : return1 = [("Make sure that each geometry\nobject has a unique family name.", "")]
OUT = output1([i[0] for i in return1]), output1([i[1] for i in return1])
satOpt.Dispose()
opt1.Dispose()
SaveAsOpt.Dispose()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7971abd8-ecd2-4e2f-a28e-52027545f3f6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-30.8885079751855" y="2.71239964797083" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="geometry:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="487f0411-0bdf-4764-973d-cae73f53aff1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-96.8885079751855" y="61.096959630846" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyTemplatePath:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5923b814-be99-4137-acdd-60f1a8177b72" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-47.8885079751855" y="119.481519613721" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyName:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3ab55325-8be4-4940-8341-2396cfdb6443" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-344.888507975185" y="177.866079596596" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category:var[] = Category.ByName(&quot;OST_GenericModel&quot;)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="325026ea-de93-449a-9cff-bea72f2165f3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="481.34169886937" y="97.2579709545968" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="instance" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="aff75132-a345-4885-beee-fdf45692a2f1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-121.888507975185" y="236.250639579471" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="materialName:var[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5340671d-e4f1-4bcc-946d-d88da17a3e84" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-80.8885079751855" y="294.635199562346" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="isVoid:var[] = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e35db8a4-f8ae-40de-ae1c-df5ba7ae6bb5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="482.081494386012" y="156.508670063082" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="family" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fba20a1f-96ab-4c49-b5cc-89d6e5b024aa" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="334.118203122638" y="101.51150541104" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="res[0];&#xA;res[1];" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9934ac47-c94d-4bb1-8e0d-a2ae0a86a302" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-146.888507975185" y="353.019759545222" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="subcategoryName:var[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1cc92fa8-a1b1-4217-a336-0a638867f39c" start_index="0" end="fba20a1f-96ab-4c49-b5cc-89d6e5b024aa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7971abd8-ecd2-4e2f-a28e-52027545f3f6" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="487f0411-0bdf-4764-973d-cae73f53aff1" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5923b814-be99-4137-acdd-60f1a8177b72" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ab55325-8be4-4940-8341-2396cfdb6443" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aff75132-a345-4885-beee-fdf45692a2f1" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5340671d-e4f1-4bcc-946d-d88da17a3e84" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fba20a1f-96ab-4c49-b5cc-89d6e5b024aa" start_index="0" end="325026ea-de93-449a-9cff-bea72f2165f3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fba20a1f-96ab-4c49-b5cc-89d6e5b024aa" start_index="1" end="e35db8a4-f8ae-40de-ae1c-df5ba7ae6bb5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9934ac47-c94d-4bb1-8e0d-a2ae0a86a302" start_index="0" end="1cc92fa8-a1b1-4217-a336-0a638867f39c" end_index="6" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-9.19272125753637" eyeY="13.0784624004798" eyeZ="20.9641004725462" lookX="1.98757174959178" lookY="-17.9107426082534" lookZ="-24.2303553944167" upX="0.0332521800396792" upY="0.913545457642601" upZ="-0.405375121761536" />
  </Cameras>
</Workspace>