<Workspace Version="1.3.2.2480" X="139.971711667902" Y="219.671776615113" zoom="2.37004060791359" ScaleFactor="1" Name="Springs.Points.ConvexHull2D" Description="Computes the XY convex hull of a given set of points based on the monotone chain algorithm." ID="f3262378-975c-40f8-bf70-5867e7837b75" Category="Springs.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="ConvexHull" resolvedName="Tessellation.ConvexHull" assemblyName="Tessellation.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="59b13e3d-6975-44b9-b83b-3cc04fddfe77" type="PythonNodeModels.PythonNode" nickname="Python Script" x="154.700792331351" y="-0.0642867484903604" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import Point

from itertools import chain

pts = sorted( (p.X, p.Y) for p in IN[0])
elev = IN[1]

def pCrs(o, a, b):
	return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

pLen = len(pts)
if pLen &lt; 4 : OUT = pts
else:
	lower, upper = [], []
	
	for i in xrange(pLen):
		j = pLen - 1 - i
		while len(lower) &gt;= 2 and pCrs(lower[-2], lower[-1], pts[i]) &lt;= 0.000001:
			lower.pop()
		lower.append(pts[i])
		while len(upper) &gt;= 2 and pCrs(upper[-2], upper[-1], pts[j]) &lt;= 0.000001:
			upper.pop()
		upper.append(pts[j])
	
	lower.pop()
	upper.pop()
	
	OUT = [Point.ByCoordinates(p[0], p[1], elev) for p in chain(lower, upper) ]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="061ebfe0-b233-4f86-b4d8-5b125cd57a70" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0.421933698798682" y="-0.421933698798654" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="points:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="cbdb1810-f723-4503-aa78-edbeaca4b18f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="298.702763576848" y="-0.972440894578028" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="69da2bf8-f129-4e7b-8de3-3710e4151a2e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-64.6713244716982" y="58.8179002894765" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elevation:double = 0" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="59b13e3d-6975-44b9-b83b-3cc04fddfe77" start_index="0" end="cbdb1810-f723-4503-aa78-edbeaca4b18f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="061ebfe0-b233-4f86-b4d8-5b125cd57a70" start_index="0" end="59b13e3d-6975-44b9-b83b-3cc04fddfe77" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="69da2bf8-f129-4e7b-8de3-3710e4151a2e" start_index="0" end="59b13e3d-6975-44b9-b83b-3cc04fddfe77" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-79326.3404835722" eyeY="20342.0635527164" eyeZ="52911.0827450261" lookX="-2.29037387877179" lookY="-6085.09625292239" lookZ="-12.5901362238874" upX="-0.174742083749757" upY="0.216439557844984" upZ="-0.960530682019644" />
  </Cameras>
</Workspace>