<Workspace Version="1.3.2.2480" X="204.186445758937" Y="242.960749802902" zoom="1.40972876398001" ScaleFactor="1" Name="Springs.Str2Ln" Description="De-serilize a Revit parameter string into a geometric line." ID="95425f93-d15f-4887-b341-c0e64bd3efce" Category="Springs.Geometry.Serialization">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="BoundingBox" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Wall" resolvedName="Revit.Elements.Wall" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Transaction" resolvedName="Revit.Transaction.Transaction" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="08d1be68-7c9e-44b8-a52b-3f4a98cce2b1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="235.588796593341" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="par;&#xA;s1;&#xA;par1 = String.ToNumber(String.Split(par, s1));&#xA;p1 = Point.ByCoordinates(par1[0],par1[1],par1[2]);&#xA;p2 = Point.ByCoordinates(par1[3],par1[4],par1[5]);&#xA;ln = Line.ByStartPointEndPoint(p1,p2);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3129cf66-2999-4314-9eee-82f8612c6121" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="124.113736612372" y="-3.13128113352978" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="str:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="44a7255b-39c3-4fec-91cf-c129f12cbefb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="742.089932117741" y="83.1725545961071" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="line" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="174c8475-cea2-446f-8a48-a8bf0f0b8198" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-4.69174502373932" y="64.6528897989109" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="separator: string = &quot;,&quot;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="08d1be68-7c9e-44b8-a52b-3f4a98cce2b1" start_index="5" end="44a7255b-39c3-4fec-91cf-c129f12cbefb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3129cf66-2999-4314-9eee-82f8612c6121" start_index="0" end="08d1be68-7c9e-44b8-a52b-3f4a98cce2b1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="174c8475-cea2-446f-8a48-a8bf0f0b8198" start_index="0" end="08d1be68-7c9e-44b8-a52b-3f4a98cce2b1" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="55.5282192569884" eyeY="195.783824846012" eyeZ="-51.2844799379119" lookX="-0.858967644938325" lookY="-87.9430536372463" lookZ="-60.7081984053477" upX="-0.00964871154219384" upY="0.731353701619171" upZ="-0.681930103084996" />
  </Cameras>
</Workspace>