<Workspace Version="1.3.2.2480" X="228.39857193783" Y="65.9104398948813" zoom="1.1988764122517" ScaleFactor="1" Name="Springs.TextNote.ByPoint" Description="Places a text note at a given point in the view. View, text type and content can either be a single item for all points or the same length as the number of points.&#xD;&#xA;Set track to false if you'd like to place notes on every run." ID="6d9eac08-17d3-49be-be91-4ce94069a40a" Category="Springs.Revit.TextNote">
  <NamespaceResolutionMap>
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="76b9e68c-7477-4f98-9050-d179a0f2ea9e" type="PythonNodeModels.PythonNode" nickname="TextNote.ByPoint" x="264.004192302455" y="109.316972529113" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="6">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <Script># Copyright(c) 2018, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com
# www.badmonkeys.net

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitAPI')
import Autodesk.Revit.DB as DB

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

def tolist(x):
	if hasattr(x,'__iter__'): return x
	else : return [x]

view = UnwrapElement(tolist(IN[0]))
pts = tolist(IN[1])
content = map(str, tolist(IN[2]))
txtType = UnwrapElement(tolist(IN[3]))
_txtAlign = str(IN[4])
persistent = not IN[5]

txtAlign_dict = {"Center" : DB.HorizontalTextAlignment.Center,
				 "Left"   : DB.HorizontalTextAlignment.Left,
				 "Right"  : DB.HorizontalTextAlignment.Right}
txtAlign = txtAlign_dict.get(_txtAlign, None)
if txtAlign is None:
	txtAlign = txtAlign_dict["Center"]

if txtType[0] is None:
	txtType[0] = doc.GetElement(doc.GetDefaultElementTypeId(DB.ElementTypeGroup.TextNoteType))

OUT = []
txtType_len = len(txtType) == 1
view_len = len(view) == 1
content_len = len(content) == 1

TransactionManager.Instance.EnsureInTransaction(doc)
for i in xrange(len(pts) ):
	p = pts[i].ToXyz(True)
	j = 0 if txtType_len else i
	k = 0 if view_len else i
	m = 0 if content_len else i
	try:
		tn = DB.TextNote.Create(doc, view[k].Id, p, content[m], txtType[j].Id)
		tn.HorizontalAlignment = txtAlign
		OUT.append(tn.ToDSType(persistent) )
	except:
		OUT.append(None)
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="eefc2086-b894-4094-8561-89a94c0e22a4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-208.795510364838" y="-6.62024350475355" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view : var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6e48c707-ad3b-4f83-a81a-bbc04d654e6b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-208.795510364838" y="57.9978833347682" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="point : var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9b9c43ce-669b-48e1-82a3-9fa225590353" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-208.795510364838" y="122.61601017429" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="content : string[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d00e87ae-a262-41bf-8284-c8ea65a67055" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-209.62962469871" y="187.234137013812" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="textType : var[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="763bcf7a-d783-4c26-bb15-46ee55daf92d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-208.795510364838" y="251.852263853334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="horAlign : string = &quot;Center&quot;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2c5d6b46-7c08-4c89-bb36-b3937acc9871" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-208.795510364838" y="316.470390692855" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="track : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0db9b4af-d038-4dcd-8131-98e9eeca3273" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="410.058714730446" y="109.746946985836" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="textNote" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="76b9e68c-7477-4f98-9050-d179a0f2ea9e" start_index="0" end="0db9b4af-d038-4dcd-8131-98e9eeca3273" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eefc2086-b894-4094-8561-89a94c0e22a4" start_index="0" end="76b9e68c-7477-4f98-9050-d179a0f2ea9e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e48c707-ad3b-4f83-a81a-bbc04d654e6b" start_index="0" end="76b9e68c-7477-4f98-9050-d179a0f2ea9e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9b9c43ce-669b-48e1-82a3-9fa225590353" start_index="0" end="76b9e68c-7477-4f98-9050-d179a0f2ea9e" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d00e87ae-a262-41bf-8284-c8ea65a67055" start_index="0" end="76b9e68c-7477-4f98-9050-d179a0f2ea9e" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="763bcf7a-d783-4c26-bb15-46ee55daf92d" start_index="0" end="76b9e68c-7477-4f98-9050-d179a0f2ea9e" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2c5d6b46-7c08-4c89-bb36-b3937acc9871" start_index="0" end="76b9e68c-7477-4f98-9050-d179a0f2ea9e" end_index="5" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-243.143306484871" eyeY="982.302281597308" eyeZ="-32.3193064921526" lookX="-0.192916648350575" lookY="-961.032803566444" lookZ="-35.5830676794502" upX="-0.00524881610456376" upY="0.250380017614603" upZ="-0.968133407738682" />
  </Cameras>
</Workspace>