<Workspace Version="1.0.0.1180" X="104.8" Y="104.8" zoom="1" Name="Springs.ViewSet.ByViewsName" Description="Creates a set of views(or sheets) for printing. If the set exists, set Overwrite to true to replace it." ID="e4edfc7e-fba0-4a8b-ab28-ff16692710b2" Category="Springs.Revit.Views">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f404bea1-281a-496d-bb41-f364a0b8c16e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com
#code inspired by Harry Mattison
#https://boostyourbim.wordpress.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

def tolist(obj1):
	if hasattr(obj1,"__iter__") : return obj1
	else : return [obj1]

def first(obj1):
	if hasattr(obj1,'__iter__') : return obj1[0]
	else : return obj1

views = UnwrapElement(tolist(IN[0]))
name1 = str(first(IN[1]) )
overwrite = IN[2]
vs_exists = None

fec = FilteredElementCollector(doc).OfClass(ViewSheetSet).GetElementIterator()
fec.Reset()
for f in fec:
	if f.Name == name1:
		vs_exists = f
		break
if vs_exists != None and overwrite:
	TransactionManager.Instance.EnsureInTransaction(doc)
	doc.Delete(vs_exists.Id)
	TransactionManager.Instance.TransactionTaskDone()
	vs_exists = None
elif vs_exists != None and not overwrite:
	OUT = "There's a ViewSet with the same name.\nSet Overwrite to true to continue."
if vs_exists == None:
	vs1 = ViewSet()
	for v in views: (vs1.Insert(v))
	printMan = doc.PrintManager
	printMan.PrintRange = PrintRange.Select
	viewSS = printMan.ViewSheetSetting
	try:
		TransactionManager.Instance.EnsureInTransaction(doc)
		viewSS.CurrentViewSheetSet.Views = vs1
		viewSS.SaveAs(name1)
		TransactionManager.Instance.TransactionTaskDone()
		OUT = "ViewSet created with %s views inside." %len(views)
	except:
		OUT = "The ViewSet could not be created"</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dea39b45-c1e8-4169-b637-16def36587d8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="views:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="db2a6155-03ae-4ef5-a30f-5fb96f4f73e7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-0.800000000000011" y="62.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="setName:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6e9ad46e-d238-419a-b92c-b844af2b4c5e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="123.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Overwrite:bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="735f552e-41cd-4c7e-b3c5-9199e59dbbc2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="401" y="0.800000000000011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f404bea1-281a-496d-bb41-f364a0b8c16e" start_index="0" end="735f552e-41cd-4c7e-b3c5-9199e59dbbc2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dea39b45-c1e8-4169-b637-16def36587d8" start_index="0" end="f404bea1-281a-496d-bb41-f364a0b8c16e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="db2a6155-03ae-4ef5-a30f-5fb96f4f73e7" start_index="0" end="f404bea1-281a-496d-bb41-f364a0b8c16e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e9ad46e-d238-419a-b92c-b844af2b4c5e" start_index="0" end="f404bea1-281a-496d-bb41-f364a0b8c16e" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>