<Workspace Version="0.8.2.2392" X="29.5541631376962" Y="158.668388669197" zoom="1.545620359375" Name="Ln2Str" Description="Serilize a geometry line to a string for use in Revit parameters" ID="6c712c67-329c-4499-a399-d1cedd2b45bf" Category="SpringNodes.Geometry.Serialization">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="BoundingBox" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Wall" resolvedName="Revit.Elements.Wall" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Transaction" resolvedName="Revit.Transaction.Transaction" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="e7e969ff-4b40-470f-858d-4acfcbbaed8a" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="def Pt2Rvt(p1)&#xA;{&#xA;return = p1.X + &quot;,&quot; + p1.Y + &quot;,&quot; + p1.Z;&#xA;};&#xA;&#xA;def Ln2Rvt(l1)&#xA;{&#xA;return = Pt2Rvt(l1.StartPoint) + &quot;,&quot; + Pt2Rvt(l1.EndPoint);&#xA;};&#xA;&#xA;Ln2Rvt(cl);" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="97bad80b-b29d-486f-9515-1789f3c00209" type="Dynamo.Nodes.Output" nickname="Output" x="822" y="167" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="string" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="f7725858-946b-4854-a550-3b8ae202997c" type="Dynamo.Nodes.Symbol" nickname="Input" x="127.5" y="1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="line:var" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="e7e969ff-4b40-470f-858d-4acfcbbaed8a" start_index="0" end="97bad80b-b29d-486f-9515-1789f3c00209" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f7725858-946b-4854-a550-3b8ae202997c" start_index="0" end="e7e969ff-4b40-470f-858d-4acfcbbaed8a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>