<Workspace Version="0.8.2.2392" X="375.35963180481" Y="92.5484466581762" zoom="0.931811528498331" Name="N-hedron.ByOriginVector" Description="Creates a multi-sided poyhedron with defined side length and total height." ID="82009e60-8e1b-45dc-8d87-b701992d1c1e" Category="SpringNodes.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Polygon" resolvedName="Autodesk.DesignScript.Geometry.Polygon" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="9ebdb791-7590-4c09-95a1-b1b34083f86b" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="221.230910568371" y="254.815482081095" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Nhedron(pt,vec,n,l,h);" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="017467f0-ce23-4107-a217-b3b0e910fa95" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="220.809547673407" y="38.6344221969609" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="def Nhedron(pt,vec,n,l,h){&#xA;r1 = l/Math.Sin(360/n)/2;&#xA;c1 = Circle.ByCenterPointRadiusNormal(pt,r1,vec);&#xA;pol1 = Polygon.RegularPolygon(c1,n);&#xA;pt2 = pt.Translate(vec,h);&#xA;l1 = Line.ByStartPointEndPoint(pt2,pol1.Points);&#xA;l1 = List.AddItemToEnd(l1[0],l1);&#xA;return = Surface.ByRuledLoft(l1).Join(pol1.Patch()).&#xA;ExtractSolids()[0];&#xA;};" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="fc1852b0-0f40-4e9f-97cd-a346139ae643" type="Dynamo.Nodes.Symbol" nickname="Input" x="-187.2" y="171.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="origin : Point = Point.Origin()" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="0d9e1f5d-27fd-43c2-b040-09a54596d2da" type="Dynamo.Nodes.Symbol" nickname="Input" x="-179.2" y="233.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="axis : Vector = Vector.ZAxis()" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="9ec92c38-59aa-478a-ba6f-d90f7d70a3bc" type="Dynamo.Nodes.Symbol" nickname="Input" x="-54.4" y="296" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="sides : int = 3" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="f3a22914-8ea7-4b9c-af2b-2e6b0f3b4ef6" type="Dynamo.Nodes.Symbol" nickname="Input" x="-96" y="358.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="length : double = 10" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="ec634aef-aeed-43e5-9861-c617b9512eee" type="Dynamo.Nodes.Symbol" nickname="Input" x="-88" y="420.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="height : double = 8" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="e7eca4b2-eb65-4a66-9b2c-de23da409de3" type="Dynamo.Nodes.Output" nickname="Output" x="490.22182312675" y="254.754734355757" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="solid" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="9ebdb791-7590-4c09-95a1-b1b34083f86b" start_index="0" end="e7eca4b2-eb65-4a66-9b2c-de23da409de3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fc1852b0-0f40-4e9f-97cd-a346139ae643" start_index="0" end="9ebdb791-7590-4c09-95a1-b1b34083f86b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0d9e1f5d-27fd-43c2-b040-09a54596d2da" start_index="0" end="9ebdb791-7590-4c09-95a1-b1b34083f86b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9ec92c38-59aa-478a-ba6f-d90f7d70a3bc" start_index="0" end="9ebdb791-7590-4c09-95a1-b1b34083f86b" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="f3a22914-8ea7-4b9c-af2b-2e6b0f3b4ef6" start_index="0" end="9ebdb791-7590-4c09-95a1-b1b34083f86b" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="ec634aef-aeed-43e5-9861-c617b9512eee" start_index="0" end="9ebdb791-7590-4c09-95a1-b1b34083f86b" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="-3.06515573117261" eyeY="8.63608441945108" eyeZ="7.57695260366139" lookX="2.64806410813747" lookY="-5.22968470077403" lookZ="-7.51958560692635" />
  </Cameras>
</Workspace>