<Workspace Version="0.8.2.2392" X="185.848120558855" Y="126.965120558855" zoom="1.33823125" Name="NullSetParameter" Description="Similar to the built-in function but with the ability to handle null values. Part of the SmartCopyMon workflow." ID="f45a0154-7a64-426c-8f02-b4225616197a" Category="SpringNodes.SmartCopyMon">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="BoundingBox" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Wall" resolvedName="Revit.Elements.Wall" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Transaction" resolvedName="Revit.Transaction.Transaction" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="43571f17-4621-42e3-9cb2-65839439b070" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="def NullSet(e1,par,val)&#xA;{&#xA;return = [Imperative]&#xA;{&#xA;if (e1 != null)&#xA;{&#xA;e1.SetParameterByName(par,val);&#xA;return = e1;&#xA;}&#xA;}&#xA;};&#xA;NullSet(e1,par,val);" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="d45ad582-feee-4abe-bea2-69eeb81cea6d" type="Dynamo.Nodes.Output" nickname="Output" x="651" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="element" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="abd3884d-d056-472b-a79b-8642086f808d" type="Dynamo.Nodes.Symbol" nickname="Input" x="65.6304763777896" y="-5.81980547745792" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="element:var" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="35315ab5-8f6e-4fc4-b21c-16740aff45af" type="Dynamo.Nodes.Symbol" nickname="Input" x="54.2015379936351" y="57.1031291797622" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="parameter:var" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="944b3137-8b3f-4188-85f5-2cabf26a1b80" type="Dynamo.Nodes.Symbol" nickname="Input" x="82.135658124218" y="126.136274609597" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="value:var" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="43571f17-4621-42e3-9cb2-65839439b070" start_index="0" end="d45ad582-feee-4abe-bea2-69eeb81cea6d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="abd3884d-d056-472b-a79b-8642086f808d" start_index="0" end="43571f17-4621-42e3-9cb2-65839439b070" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="35315ab5-8f6e-4fc4-b21c-16740aff45af" start_index="0" end="43571f17-4621-42e3-9cb2-65839439b070" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="944b3137-8b3f-4188-85f5-2cabf26a1b80" start_index="0" end="43571f17-4621-42e3-9cb2-65839439b070" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>