<Workspace Version="0.8.2.2392" X="164.706675" Y="145.00055" zoom="1.33823125" Name="Point.PullOntoPlane" Description="Pulls (projects) the point onto the input plane, following the plane normal." ID="fdde0542-4887-461f-b536-3633df7b61d3" Category="SpringNodes.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector.XAxis" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="f4cfe995-3f3f-4f11-9a14-2daf8358a6c7" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="235.054899891181" y="-2.98902002176379" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="def PtProj1(pt1,pl1){&#xA;l1 = Line.ByStartPointEndPoint(pt1,&#xA;pt1.Add(pl1.XAxis));&#xA;return = l1.PullOntoPlane(pl1).StartPoint;&#xA;};" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="195bc830-dd4c-4773-ace3-0fcffcd12a88" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="285.688298856906" y="155.78645647525" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="PtProj1(pt,pl);" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="df52bd90-92ad-401e-a36d-d1bc8b05ca97" type="Dynamo.Nodes.Symbol" nickname="Input" x="144.967471055544" y="138.989431012017" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="point:var" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="fcfce7bd-0637-4b3d-bbab-bfc9a2d4c729" type="Dynamo.Nodes.Symbol" nickname="Input" x="141.97845103378" y="196.329810337339" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="plane:var" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="b55a23d1-ed5a-4e46-86f2-80ecd165bcaf" type="Dynamo.Nodes.Output" nickname="Output" x="499.669778672408" y="155.429041131718" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="point" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="195bc830-dd4c-4773-ace3-0fcffcd12a88" start_index="0" end="b55a23d1-ed5a-4e46-86f2-80ecd165bcaf" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="df52bd90-92ad-401e-a36d-d1bc8b05ca97" start_index="0" end="195bc830-dd4c-4773-ace3-0fcffcd12a88" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fcfce7bd-0637-4b3d-bbab-bfc9a2d4c729" start_index="0" end="195bc830-dd4c-4773-ace3-0fcffcd12a88" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>